[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_ACCESS_TOKEN = ""
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = ""

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://app.contentful.com"

[[redirects]]
  from = "/"
  to = "/en/home/"
  status = 301
  force = true

[[redirects]]
  from = "/en/"
  to = "/en/home/"
  status = 302
  force = true
  
[[redirects]]
  from = "/fr/"
  to = "/fr/accueil/"
  status = 302
  force = true